# Generated by Django 4.1.4 on 2024-04-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='')),
                ('email', models.EmailField(max_length=254, verbose_name='')),
                ('password', models.CharField(max_length=50, verbose_name='')),
            ],
        ),
    ]
